core_homepage:
    path:     /
    defaults: { _controller: "CoreBundle:Default:index" }
    
core_links:
    path:     /links
    defaults: { _controller: "CoreBundle:Default:links" }
    
core_categories:
    path:     /categories
    defaults: { _controller: "CoreBundle:Default:categories" }