services:
    corebundle.doctrine_listener.link_update:
        class:  CoreBundle\DoctrineListener\LinkUpdateListener
        tags:
            - { name: doctrine.event_listener, event: onFlush }
    
    NotificationManager:
        class: CoreBundle\Service\NotificationManagerService
        arguments: ['@doctrine.orm.entity_manager']