# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
      UserBundle\Entity\User: sha512
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
      main:
        id: fos_user.user_provider.username

    firewalls:
#        main_login:
#          pattern:      ^/(login|register)
#          anonymous:    true
#          form_login:
#            check_path: fos_user_security_check
        main:
          pattern:      ^/
          anonymous:    true
          form_login:
            login_path: fos_user_security_login
            check_path: fos_user_security_check
          provider:     main
          logout:
            path:       fos_user_security_logout
            target:     fos_user_security_login
          remember_me:
            secret: '%secret%'