<?php

namespace CoreBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUserQB($user) {
        $query = $this->createQueryBuilder('c')
        ->where('c.user = :id')
        ->setParameter('id', $user->getId());
        
        return $query;
    }
    
    public function findByUserWithLinks($user){
        $query = $this->createQueryBuilder('c')
        ->leftJoin('c.links', 'l')
        ->where('c.user = :id')
        ->setParameter('id', $user->getId());
        
        return $query->getQuery()->getResult();
    }
}