<?php

namespace CoreBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNotifByUser($user){
        $query = $this->createQueryBuilder('n')
        ->innerJoin('n.userReceiver', 'u')
        ->where('n.userReceiver = :id')
        ->addSelect('u')
        ->setParameter('id', $user->getId());
        
        return $query->getQuery()->getResult();
    }
}